### ISSUE TITLE
Missing import for TAILQ when config has list entry

### ISSUE THREAD

**Issue by mbucc** [kristapsdz/kwebapp#6]
Hi,

The generated db.h did not include the TAILQ import when my config included a list entry.

```
#include <sys/queue.h>
```

**Comment by kristapsdz** [comment]
That's intentional.  I don't put inclusion in header files unless it's in, say, config.h.  This is noted in [kwebapp-c-header(1)](https://kristaps.bsd.lv/kwebapp/kwebapp-c-header.1.html).

```
   Data structures
     The basis of the C API is a series of enumerations, structures, and
     preprocessor macros that describe the data.  To include output files for
     data structures, you'll need:

           #include <sys/queue.h> /* iff you have lists */
           #include <stdint.h>
```

**Comment by mbucc** [comment]
Sorry, I meant to say db.c not db.h.

I was surprised my main routine stopped compiling after adding the list stanza to configure file.   The code in my main, paraphrased, goes like this:
```
        struct act_q   *acts;
        acts = db_act_list_by...
        json_act_array(&req, acts);
```
I fixed it by adding the import to my main routine, but I thought that include should have been db.c's responsibility.  No big deal either way.

**Comment by kristapsdz** [comment]
The queue macros (sys/queue.h) are always included in the output of `kwebapp-c-source` (db.c in this case), regardless of whether they're needed.  This doesn't affect your sources, however---you must include them prior to the db.h inclusion as mentioned in `kwebapp-c-header`.  That's just how C works: db.h (or whatever you've named it) requires sys/queue.h in every file that includes it.  Is that what you mean in this?  (I'm not aware of your level of C knowledge---I apologise for sounding pedantic if I'm just misunderstanding you!)

**Comment by mbucc** [comment]
Nope, you nailed it.  My lack of C knowledge is the issue here.
